name: investMX
favicon: null
layout_spectrum: 0.239123550709337
typography_spectrum: 0.5785446013323963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08766758185811341
  lightness: 0.7003978220745921
  saturation: 0.12210832117125392
  rhythmicContrast: 0.6706630943808705
purpose: []
